config/routes.rb
Rails.application.routes.draw do
  resources :applications
  devise_for :users

  
  get 'about' => 'welcome#about'
  get 'welcome/index'
  
  root to: 'welcome#index'
  

  namespace :api, defaults: { format: :json } do
    resources :events, only: [:create]
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy

  validates_presence_of :user
  validates :name, length: { minimum: 2 }, presence: true
  validates_uniqueness_of :name
  validates :url, presence: true
  validates_uniqueness_of :url
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :application

  validates_presence_of :application
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
skip_before_action :verify_authenticity_token

  def create
    registered_application = Application.find_by(url: request.env['HTTP_ORIGIN'])
    return render json: "Unregistered application", status: :unprocessable_entity if registered_application.blank?

    @event = Event.new(event_params)
    @event.application = registered_application

    if @event.save
      render json: @event, status: :created
    else
      render @event.errors, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  def index
    @applications = Application.where(user_id: current_user)
  end

  def show
    @event_names = @application.events.pluck(:name)
  end

  def new
    @application = current_user.applications.build
  end

  def create
    @application = current_user.applications.build(application_params)
    if @application.save
      redirect_to @application, notice: "Your application has been successfully added."
    else
      flash[:error] = "There was a problem adding your application. Please try again."
      render 'new'
    end
  end

  def edit
  end

  def update
    if @application.update(application_params)
      redirect_to @application, notice: "Your application has been successfully updated."
    else
      flash[:error] = "Ther was a problem updating your application. Please try again."
      render 'edit'
    end
  end

  def destroy
    @application.destroy
    redirect_to applications_path, notice: "Your application has been successfully removed."
  end

  private

  def set_application
    @application = Application.find(params[:id])
  end

  def application_params
    params.require(:application).permit(:name, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def index
    redirect_to applications_path if current_user
  end
end

app/helpers/api/events_helper.rb
module API::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/_form.html.erb
<%= form_for @application do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being added:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter an application name" %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control", placeholder: "Enter application URL" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Edit <%= @application.name %></h1>
    </div>
  </div>

  <div class="panel-body">
    <%= render partial: 'form'%>
  </div>
  <div class="panel-footer">
    <%= link_to "Back", @application %>
</div>

app/views/applications/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1><%= current_user.name %>'s Applications</h1>
    </div>
  </div>
  <ul class="list-group">
    <% @applications.each do |application| %>
      <li class="list-group-item"><%= link_to application.name, application %></li>
    <% end %>
  </ul> 
  <div class="panel-footer">
    <%= link_to "Add Application", new_application_path, class: 'btn btn-success' %>
</div>

app/views/applications/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Add an Application</h1>
    </div>
  </div>

  <div class="panel-body">
    <%= render partial: 'form'%>
  </div>
  <div class="panel-footer">
    <%= link_to "Back", applications_path %>
</div>

app/views/applications/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-heading">
      <h1><%= @application.name %></h1>
    </div>
  </div>
  <ul class="list-group">
    <li class="list-group-item"><strong>URL: </strong><%= link_to @application.url, @application.url %></li>
  </ul>
  <table class="table">
    <tr>
      <td><strong>Events</strong></td>
      <td><strong>Count</strong></td>
    </tr>
    <% unless @event_names.blank? %>
      <% @event_names.uniq.each do |name| %>
        <tr>
          <td><%= name.capitalize.titleize %></td>
          <td><%= @event_names.count(name) %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
  <% if Rails.env.production? %>
    <%= line_chart @application.events.group_by_day(:created_at).count %>
  <% else %>
    <%= pie_chart @application.events.group(:name).count %>
  <% end %>
  <div class="panel-footer">
    <%= link_to "Edit", edit_application_path(@application) , class: "btn btn-success" %>
    <%= link_to "Remove", application_path, method: "delete", class: "btn btn-danger" %>
    <p id="show-appliscations-link"><%= link_to "Applications", applications_path %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blocmetrics</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  </head>
  <body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Blocmetrics", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "About", about_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to "Applications", applications_path %></li>
            <li><%= link_to current_user.name, edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/welcome/about.html.erb
<div class="well well-lg">
  <h1>About Blocmetrics</h1>
  <p>Blocmetrics is an api that allows other developers to track events on their own applications.</p>
  <p>Created by: Matthew T Farley</p>
</div>

app/views/welcome/index.html.erb
<div class="well well-lg">
  <h1>Welcome to Blocmetrics</h1>
  <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %> or <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary" %> to get started!</p>
</div>